create table public.app_complaints (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  fk_app_orders_id bigint null,
  description text null,
  stage text null,
  improvement_idea text null,
  fk_app_order_items_id bigint null,
  constraint app_complaints_pkey primary key (id),
  constraint app_complaints_fk_app_order_items_id_fkey foreign KEY (fk_app_order_items_id) references app_order_items (id) on update RESTRICT on delete RESTRICT,
  constraint app_complaints_fk_app_orders_id_fkey foreign KEY (fk_app_orders_id) references app_orders (id) on delete CASCADE,
  constraint app_complaints_stage_fkey foreign KEY (stage) references app_complaints_stages (id) on update CASCADE
) TABLESPACE pg_default;