create table public.app_order_item_attributes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "bb_Name" text null,
  "bb_Value" text null,
  fk_app_order_items_id bigint null,
  constraint app_order_item_attributes_pkey primary key (id),
  constraint app_order_item_attributes_fk_app_order_items_id_fkey foreign KEY (fk_app_order_items_id) references app_order_items (id) on delete CASCADE
) TABLESPACE pg_default;