create table public.app_orders (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "bb_OrderNumber" text null,
  "bb_State" smallint null,
  "bb_VatMode" smallint null,
  "bb_CreatedAt" text null,
  offered_at timestamp with time zone null,
  "bb_ConfirmedAt" text null,
  "bb_ShippedAt" text null,
  "bb_PayedAt" text null,
  "bb_SellerComment" text null,
  "bb_InvoiceNumberPrefix" text null,
  "bb_InvoiceNumber" text null,
  "bb_InvoiceDate" text null,
  "bb_Currency" text null,
  "bb_LastModifiedAt" text null,
  "bb_WebUrl" text null,
  fk_app_customers_id bigint null,
  bb_import_ab - nummer text null,
  "bb_Platform" text null,
  "bb_BillbeeShopName" text null,
  ordered_at timestamp with time zone null,
  confirmed_at timestamp with time zone null,
  "bb_TotalCost" numeric null,
  "bb_ShippingCost" numeric null,
  "bb_AdjustmentCost" numeric null,
  "bb_PaidAmount" numeric null,
  constraint app_order_pkey primary key (id),
  constraint app_orders_fk_app_customers_id_fkey foreign KEY (fk_app_customers_id) references app_customers (id) on delete RESTRICT
) TABLESPACE pg_default;

create trigger app_orders_state_timestamps_trg BEFORE INSERT
or
update OF "bb_State" on app_orders for EACH row
execute FUNCTION trgfn_app_orders_on_state_change_set_timestamps ();