create table public.app_customers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "bb_Name" text null,
  "bb_Email" text null,
  "bb_Tel1" text null,
  "bb_Tel2" text null,
  "bb_Number" bigint null,
  "bb_PriceGroupId" bigint null,
  "bb_VatId" text null,
  "bb_Type" smallint null,
  "bb_ShippingAddress_CountryISO2" text null,
  "bb_InvoiceAddress_CountryISO2" text null,
  "bb_InvoiceAddress_Zip" text null,
  "bb_ShippingAddress_Zip" text null,
  constraint app_customers_pkey primary key (id)
) TABLESPACE pg_default;