create table public.app_stock_locations (
  id bigint generated by default as identity not null,
  name text null,
  fk_app_stocks bigint null,
  created_at timestamp with time zone not null default now(),
  constraint app_stock_locations_pkey primary key (id),
  constraint app_stock_locations_fk_app_stocks_fkey foreign KEY (fk_app_stocks) references app_stocks (id)
) TABLESPACE pg_default;