create table public.app_stocks (
  id bigint generated by default as identity not null,
  "bb_Name" text null,
  "bb_Description" text null,
  "bb_isDefault" boolean null,
  created_at timestamp with time zone not null default now(),
  constraint app_stocks_pkey primary key (id)
) TABLESPACE pg_default;