create table public.app_stock_levels (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  fk_stocks bigint null,
  "bb_StockCode" bigint null,
  fk_products bigint null,
  "bb_StockCurrent" numeric null,
  "bb_UnfullfilledAmount" numeric null,
  upsert_match_id text not null,
  constraint app_stock_levels_pkey primary key (id),
  constraint app_stock_levels_upsert_match_id_key unique (upsert_match_id),
  constraint app_stock_levels_fk_products_fkey foreign KEY (fk_products) references app_products (id),
  constraint app_stock_levels_fk_stocks_fkey foreign KEY (fk_stocks) references app_stocks (id)
) TABLESPACE pg_default;