alter table "public"."app_complaint_timeline" drop constraint "app_complaint_timeline_fk_complaint_fkey";


  create table "public"."app_order_payments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "fk_order" bigint,
    "bb_TransactionId" text,
    "bb_PayDate" timestamp with time zone,
    "bb_PaymentType" numeric,
    "bb_SourceTechnology" text,
    "bb_SourceText" text,
    "bb_PayValue" numeric,
    "bb_Purpose" text,
    "bb_Name" text
      );


alter table "public"."app_order_payments" enable row level security;

alter table "public"."app_complaint_causes" add column "fk_complaint_responsibilities" bigint;

alter table "public"."app_complaint_timeline" alter column "created_by" set not null;

CREATE UNIQUE INDEX app_order_payments_pkey ON public.app_order_payments USING btree (id);

alter table "public"."app_order_payments" add constraint "app_order_payments_pkey" PRIMARY KEY using index "app_order_payments_pkey";

alter table "public"."app_complaint_causes" add constraint "app_complaint_causes_fk_complaint_responsibilities_fkey" FOREIGN KEY (fk_complaint_responsibilities) REFERENCES public.app_complaint_responsibilities(id) not valid;

alter table "public"."app_complaint_causes" validate constraint "app_complaint_causes_fk_complaint_responsibilities_fkey";

alter table "public"."app_complaint_timeline" add constraint "app_complaint_timeline_created_by_fkey1" FOREIGN KEY (created_by) REFERENCES public.users(id) not valid;

alter table "public"."app_complaint_timeline" validate constraint "app_complaint_timeline_created_by_fkey1";

alter table "public"."app_order_payments" add constraint "app_order_payments_fk_order_fkey" FOREIGN KEY (fk_order) REFERENCES public.app_orders(id) not valid;

alter table "public"."app_order_payments" validate constraint "app_order_payments_fk_order_fkey";

alter table "public"."app_complaint_timeline" add constraint "app_complaint_timeline_fk_complaint_fkey" FOREIGN KEY (fk_complaint) REFERENCES public.app_complaints(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."app_complaint_timeline" validate constraint "app_complaint_timeline_fk_complaint_fkey";

grant delete on table "public"."app_order_payments" to "anon";

grant insert on table "public"."app_order_payments" to "anon";

grant references on table "public"."app_order_payments" to "anon";

grant select on table "public"."app_order_payments" to "anon";

grant trigger on table "public"."app_order_payments" to "anon";

grant truncate on table "public"."app_order_payments" to "anon";

grant update on table "public"."app_order_payments" to "anon";

grant delete on table "public"."app_order_payments" to "authenticated";

grant insert on table "public"."app_order_payments" to "authenticated";

grant references on table "public"."app_order_payments" to "authenticated";

grant select on table "public"."app_order_payments" to "authenticated";

grant trigger on table "public"."app_order_payments" to "authenticated";

grant truncate on table "public"."app_order_payments" to "authenticated";

grant update on table "public"."app_order_payments" to "authenticated";

grant delete on table "public"."app_order_payments" to "service_role";

grant insert on table "public"."app_order_payments" to "service_role";

grant references on table "public"."app_order_payments" to "service_role";

grant select on table "public"."app_order_payments" to "service_role";

grant trigger on table "public"."app_order_payments" to "service_role";

grant truncate on table "public"."app_order_payments" to "service_role";

grant update on table "public"."app_order_payments" to "service_role";


  create policy "authenticated"
  on "public"."app_order_payments"
  as permissive
  for all
  to public
using ((auth.role() = 'authenticated'::text));



