
  create table "public"."app_complaint_causes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "label" text
      );


alter table "public"."app_complaint_causes" enable row level security;


  create table "public"."app_complaint_responsibilities" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "label" text
      );


alter table "public"."app_complaint_responsibilities" enable row level security;


  create table "public"."app_complaint_timeline" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid,
    "event" text,
    "fk_complaint" bigint,
    "message" text,
    "is_solution" boolean
      );


alter table "public"."app_complaint_timeline" enable row level security;

alter table "public"."app_complaints" add column "fk_cause" bigint;

alter table "public"."app_complaints" add column "fk_responsibility" bigint;

alter table "public"."app_complaints" add column "is_external" boolean;

alter table "public"."app_complaints" alter column "stage" set not null;

alter table "public"."app_complaints_stages" add column "name" text;

alter table "public"."app_orders" add column "bb_ShippingProviderName" text;

alter table "public"."app_orders" add column "bb_ShippingProviderProductName" text;

CREATE UNIQUE INDEX app_complaint_causes_pkey ON public.app_complaint_causes USING btree (id);

CREATE UNIQUE INDEX app_complaint_responsibilities_pkey ON public.app_complaint_responsibilities USING btree (id);

CREATE UNIQUE INDEX app_complaint_timeline_pkey ON public.app_complaint_timeline USING btree (id);

alter table "public"."app_complaint_causes" add constraint "app_complaint_causes_pkey" PRIMARY KEY using index "app_complaint_causes_pkey";

alter table "public"."app_complaint_responsibilities" add constraint "app_complaint_responsibilities_pkey" PRIMARY KEY using index "app_complaint_responsibilities_pkey";

alter table "public"."app_complaint_timeline" add constraint "app_complaint_timeline_pkey" PRIMARY KEY using index "app_complaint_timeline_pkey";

alter table "public"."app_complaint_timeline" add constraint "app_complaint_timeline_fk_complaint_fkey" FOREIGN KEY (fk_complaint) REFERENCES public.app_complaints(id) not valid;

alter table "public"."app_complaint_timeline" validate constraint "app_complaint_timeline_fk_complaint_fkey";

alter table "public"."app_complaints" add constraint "app_complaints_fk_cause_fkey" FOREIGN KEY (fk_cause) REFERENCES public.app_complaint_causes(id) not valid;

alter table "public"."app_complaints" validate constraint "app_complaints_fk_cause_fkey";

alter table "public"."app_complaints" add constraint "app_complaints_fk_responsibility_fkey" FOREIGN KEY (fk_responsibility) REFERENCES public.app_complaint_responsibilities(id) not valid;

alter table "public"."app_complaints" validate constraint "app_complaints_fk_responsibility_fkey";

create or replace view "public"."app_component_sales_last_3_months" as  WITH order_items_3m AS (
         SELECT oi.id,
            oi.fk_app_orders_id,
            oi.fk_app_products_id,
            oi."bb_Quantity",
            o.created_at
           FROM (public.app_order_items oi
             JOIN public.app_orders o ON ((o.id = oi.fk_app_orders_id)))
          WHERE ((o.ordered_at >= (now() - '1 year'::interval)) AND (COALESCE(oi."bb_IsCoupon", false) = false))
        ), direct_component_sales AS (
         SELECT oi.fk_app_products_id AS component_id,
            sum(COALESCE((oi."bb_Quantity")::integer, 0)) AS qty_component_sold
           FROM (order_items_3m oi
             LEFT JOIN public.bom_recipes br ON ((br.billbee_bom_id = oi.fk_app_products_id)))
          WHERE ((br.billbee_bom_id IS NULL) AND (oi.fk_app_products_id IS NOT NULL))
          GROUP BY oi.fk_app_products_id
        ), bom_component_sales AS (
         SELECT br.billbee_component_id AS component_id,
            sum(((COALESCE((oi."bb_Quantity")::integer, 0))::numeric * br.quantity)) AS qty_component_sold
           FROM (order_items_3m oi
             JOIN public.bom_recipes br ON ((br.billbee_bom_id = oi.fk_app_products_id)))
          GROUP BY br.billbee_component_id
        ), all_component_sales AS (
         SELECT direct_component_sales.component_id,
            direct_component_sales.qty_component_sold
           FROM direct_component_sales
        UNION ALL
         SELECT bom_component_sales.component_id,
            bom_component_sales.qty_component_sold
           FROM bom_component_sales
        )
 SELECT cs.component_id AS fk_app_products_id,
    (sum(cs.qty_component_sold) / (4)::numeric) AS qty_sold_last_3_months
   FROM all_component_sales cs
  GROUP BY cs.component_id;


grant delete on table "public"."app_complaint_causes" to "anon";

grant insert on table "public"."app_complaint_causes" to "anon";

grant references on table "public"."app_complaint_causes" to "anon";

grant select on table "public"."app_complaint_causes" to "anon";

grant trigger on table "public"."app_complaint_causes" to "anon";

grant truncate on table "public"."app_complaint_causes" to "anon";

grant update on table "public"."app_complaint_causes" to "anon";

grant delete on table "public"."app_complaint_causes" to "authenticated";

grant insert on table "public"."app_complaint_causes" to "authenticated";

grant references on table "public"."app_complaint_causes" to "authenticated";

grant select on table "public"."app_complaint_causes" to "authenticated";

grant trigger on table "public"."app_complaint_causes" to "authenticated";

grant truncate on table "public"."app_complaint_causes" to "authenticated";

grant update on table "public"."app_complaint_causes" to "authenticated";

grant delete on table "public"."app_complaint_causes" to "service_role";

grant insert on table "public"."app_complaint_causes" to "service_role";

grant references on table "public"."app_complaint_causes" to "service_role";

grant select on table "public"."app_complaint_causes" to "service_role";

grant trigger on table "public"."app_complaint_causes" to "service_role";

grant truncate on table "public"."app_complaint_causes" to "service_role";

grant update on table "public"."app_complaint_causes" to "service_role";

grant delete on table "public"."app_complaint_responsibilities" to "anon";

grant insert on table "public"."app_complaint_responsibilities" to "anon";

grant references on table "public"."app_complaint_responsibilities" to "anon";

grant select on table "public"."app_complaint_responsibilities" to "anon";

grant trigger on table "public"."app_complaint_responsibilities" to "anon";

grant truncate on table "public"."app_complaint_responsibilities" to "anon";

grant update on table "public"."app_complaint_responsibilities" to "anon";

grant delete on table "public"."app_complaint_responsibilities" to "authenticated";

grant insert on table "public"."app_complaint_responsibilities" to "authenticated";

grant references on table "public"."app_complaint_responsibilities" to "authenticated";

grant select on table "public"."app_complaint_responsibilities" to "authenticated";

grant trigger on table "public"."app_complaint_responsibilities" to "authenticated";

grant truncate on table "public"."app_complaint_responsibilities" to "authenticated";

grant update on table "public"."app_complaint_responsibilities" to "authenticated";

grant delete on table "public"."app_complaint_responsibilities" to "service_role";

grant insert on table "public"."app_complaint_responsibilities" to "service_role";

grant references on table "public"."app_complaint_responsibilities" to "service_role";

grant select on table "public"."app_complaint_responsibilities" to "service_role";

grant trigger on table "public"."app_complaint_responsibilities" to "service_role";

grant truncate on table "public"."app_complaint_responsibilities" to "service_role";

grant update on table "public"."app_complaint_responsibilities" to "service_role";

grant delete on table "public"."app_complaint_timeline" to "anon";

grant insert on table "public"."app_complaint_timeline" to "anon";

grant references on table "public"."app_complaint_timeline" to "anon";

grant select on table "public"."app_complaint_timeline" to "anon";

grant trigger on table "public"."app_complaint_timeline" to "anon";

grant truncate on table "public"."app_complaint_timeline" to "anon";

grant update on table "public"."app_complaint_timeline" to "anon";

grant delete on table "public"."app_complaint_timeline" to "authenticated";

grant insert on table "public"."app_complaint_timeline" to "authenticated";

grant references on table "public"."app_complaint_timeline" to "authenticated";

grant select on table "public"."app_complaint_timeline" to "authenticated";

grant trigger on table "public"."app_complaint_timeline" to "authenticated";

grant truncate on table "public"."app_complaint_timeline" to "authenticated";

grant update on table "public"."app_complaint_timeline" to "authenticated";

grant delete on table "public"."app_complaint_timeline" to "service_role";

grant insert on table "public"."app_complaint_timeline" to "service_role";

grant references on table "public"."app_complaint_timeline" to "service_role";

grant select on table "public"."app_complaint_timeline" to "service_role";

grant trigger on table "public"."app_complaint_timeline" to "service_role";

grant truncate on table "public"."app_complaint_timeline" to "service_role";

grant update on table "public"."app_complaint_timeline" to "service_role";


  create policy "authenticated"
  on "public"."app_complaint_causes"
  as permissive
  for all
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "authenticated"
  on "public"."app_complaint_responsibilities"
  as permissive
  for all
  to public
using ((auth.role() = 'authenticated'::text));



